Vagrant.configure("2") do |config|
    config.vm.define :lesson_5_vm do |lesson_5_vm|
      lesson_5_vm.vm.box = "centos/7"
    end
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 20000
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
    end
  
    $script = <<-SCRIPT
      yum install -y http://download.zfsonlinux.org/epel/zfs-release.el7_8.noarch.rpm
      rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
      yum install -y epel-release kernel-devel zfs
      yum-config-manager --disable zfs
      yum-config-manager --enable zfs-kmod
      yum install -y zfs
      modprobe zfs
      yum install wget -y
    SCRIPT
  
    config.vm.provision "shell",
      inline: $script
  end